### ISSUE TITLE
Doesn't work on iOS 8

### ISSUE THREAD

**Issue by antoniogermano** [YuAo/UIControl-Sound#1]
For some reason that I haven't yet figured out, this project simply does not work at all on iOS 8.1.

I haven't tested 8.0 (because I don't have any device with 8.0 to test with), but it simply does not work on iOS 8. No sound is played.

**Comment by YuAo** [comment]
Have you tried it on a real device? It may not work on an iOS 8 simulator.

**Comment by antoniogermano** [comment]
I'm really sorry about this, I have just tested the code on an iPad and iPhone running iOS 8, and it is working on the real devices.

For some very strange reason, it isn't working on iOS 8 simulator for any device, even though it works on iOS 7 and 7.1 simulators.
However (and I don't know if this is intended or not), by playing the sound the way you do on this snippet:

```
if (soundFileToPlay) {
    NSURL *filePath = [NSURL fileURLWithPath:soundFileToPlay];
    SystemSoundID sound;
    AudioServicesCreateSystemSoundID((__bridge CFURLRef)filePath, &sound);
    CFStringRef currentRunLoopMode = CFRunLoopCopyCurrentMode(CFRunLoopGetCurrent());
    AudioServicesAddSystemSoundCompletion(sound, CFRunLoopGetCurrent(), currentRunLoopMode, &WUUIControlSoundManagerAudioServicesSystemSoundCompletionProc, NULL);
    CFRelease(currentRunLoopMode);
    AudioServicesPlaySystemSound(sound);
}
```

it plays the sounds at full volume, even if the device is set to minimum volume. This only respects the mute switch, but ignores completely the sound volume. For people who don't want this, I suggest the following change:

```
if (soundFileToPlay) {
    NSError *error;
    if (![[urlAudio absoluteString] isEqualToString:soundFileToPlay]) {
        // cache the sound URL and the audioPlayer in static variables so they are only recreated if the sound to be played is changed (which is normally not the case, all types of controls usually play the same sound, so buttons play X, switches play Y, etc)
        urlAudio = [NSURL URLWithString:soundFileToPlay];
        audioPlayer = [[AVAudioPlayer alloc] initWithContentsOfURL:urlAudio error:&error];
        [audioPlayer prepareToPlay];
        if (error) {
            NSLog(@"Failed to reproduce sound: %@", error.debugDescription);
        }
    }
    [audioPlayer play];
}
```

The audioPlayer will respect both mute switch and volume. `#import <AVFoundation/AVFoundation.h>` is necessary.
Also, the code I wrote above works on iOS 8 simulator too.

**Comment by YuAo** [comment]
`AudioServicesPlaySystemSound` **do** respect system volume. 

https://developer.apple.com/library/ios/documentation/AudioToolbox/Reference/SystemSoundServicesReference/index.html#//apple_ref/c/func/AudioServicesPlaySystemSound

> In addition, when you use the AudioServicesPlaySystemSound function:
> - Sounds play at the **current system audio volume**, with no programmatic volume control available
> - Sounds play immediately
> - Looping and stereo positioning are unavailable
> - Simultaneous playback is unavailable: You can play only one sound at a time
> - The sound is played locally on the device speakers; it does not use audio routing.

**Comment by YuAo** [comment]
It's apple's suggestion to use `AudioServicesPlaySystemSound` for playing user-interface sound effects.

> To play user-interface sound effects (such as button clicks), or to invoke vibration on devices that support it, use System Sound Services. This compact interface is described in System Sound Services Reference. 

https://developer.apple.com/library/ios/documentation/AudioVideo/Conceptual/MultimediaPG/UsingAudio/UsingAudio.html#//apple_ref/doc/uid/TP40009767-CH2-SW1

> Playing UI Sound Effects or Invoking Vibration Using System Sound Services

**Comment by antoniogermano** [comment]
Thank you very much for the info!

Sorry I should have tested on a real device before opening the issue (it would be great if I could find a way to fix it on iOS 8 simulator, though, because it works on iOS 7 simulator, and I very often don't have real devices to test with; which is why I opened the issue before being able to test on a real device in the first place)

**Comment by YuAo** [comment]
You're welcome :)
